# Generated by Django 4.2.7 on 2023-12-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='confirmpassword',
        ),
    ]
