# Generated by Django 4.2.7 on 2023-12-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_student_confirmpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('rollno', models.IntegerField()),
                ('place', models.CharField(max_length=35)),
            ],
        ),
    ]
